spring:
  datasource:
    url: jdbc:h2:mem:quizDB;
    username: test
    password: test
    driver-class-name: org.h2.Driver
    hikari:
    connection-test-query: select 1
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
jpa:
  hibernate:
    ddl-auto: create-drop


